import { generateNumericId } from "../libs/functions";

export const pairsdata = [
  // Forex Pairs
  { pair: "AUDCAD", id: generateNumericId() },
  { pair: "AUDCHF", id: generateNumericId() },
  { pair: "AUDJPY", id: generateNumericId() },
  { pair: "AUDNZD", id: generateNumericId() },
  { pair: "AUDUSD", id: generateNumericId() },
  { pair: "CADCHF", id: generateNumericId() },
  { pair: "CADJPY", id: generateNumericId() },
  { pair: "CHFJPY", id: generateNumericId() },
  { pair: "EURAUD", id: generateNumericId() },
  { pair: "EURCAD", id: generateNumericId() },
  { pair: "EURCHF", id: generateNumericId() },
  { pair: "EURGBP", id: generateNumericId() },
  { pair: "EURJPY", id: generateNumericId() },
  { pair: "EURNZD", id: generateNumericId() },
  { pair: "EURUSD", id: generateNumericId() },
  { pair: "GBPAUD", id: generateNumericId() },
  { pair: "GBPCAD", id: generateNumericId() },
  { pair: "GBPCHF", id: generateNumericId() },
  { pair: "GBPJPY", id: generateNumericId() },
  { pair: "GBPNZD", id: generateNumericId() },
  { pair: "GBPUSD", id: generateNumericId() },
  { pair: "NZDCAD", id: generateNumericId() },
  { pair: "NZDCHF", id: generateNumericId() },
  { pair: "NZDJPY", id: generateNumericId() },
  { pair: "NZDUSD", id: generateNumericId() },
  { pair: "USDCAD", id: generateNumericId() },
  { pair: "USDCHF", id: generateNumericId() },
  { pair: "USDJPY", id: generateNumericId() },
  { pair: "AUDSGD", id: generateNumericId() },
  { pair: "CADSGD", id: generateNumericId() },
  { pair: "CHFSGD", id: generateNumericId() },
  { pair: "EURAED", id: generateNumericId() },
  { pair: "EURCZK", id: generateNumericId() },
  { pair: "EURDKK", id: generateNumericId() },
  { pair: "EURHKD", id: generateNumericId() },
  { pair: "EURHUF", id: generateNumericId() },
  { pair: "EURILS", id: generateNumericId() },
  { pair: "EURINR", id: generateNumericId() },
  { pair: "EURMXN", id: generateNumericId() },
  { pair: "EURNOK", id: generateNumericId() },
  { pair: "EURPLN", id: generateNumericId() },
  { pair: "EURRON", id: generateNumericId() },
  { pair: "EURRUB", id: generateNumericId() },
  { pair: "EURSEK", id: generateNumericId() },
  { pair: "EURSGD", id: generateNumericId() },
  { pair: "EURTRY", id: generateNumericId() },
  { pair: "EURZAR", id: generateNumericId() },
  { pair: "GBPAED", id: generateNumericId() },
  { pair: "GBPCZK", id: generateNumericId() },
  { pair: "GBPDKK", id: generateNumericId() },
  { pair: "GBPHKD", id: generateNumericId() },
  { pair: "GBPHUF", id: generateNumericId() },
  { pair: "GBPINR", id: generateNumericId() },
  { pair: "GBPMXN", id: generateNumericId() },
  { pair: "GBPNOK", id: generateNumericId() },
  { pair: "GBPPLN", id: generateNumericId() },
  { pair: "GBPRON", id: generateNumericId() },
  { pair: "GBPRUB", id: generateNumericId() },
  { pair: "GBPSEK", id: generateNumericId() },
  { pair: "GBPSGD", id: generateNumericId() },
  { pair: "GBPTRY", id: generateNumericId() },
  { pair: "GBPZAR", id: generateNumericId() },
  { pair: "NZDSGD", id: generateNumericId() },
  { pair: "SGDJPY", id: generateNumericId() },
  { pair: "USDCNH", id: generateNumericId() },
  { pair: "USDCZK", id: generateNumericId() },
  { pair: "USDDKK", id: generateNumericId() },
  { pair: "USDHKD", id: generateNumericId() },
  { pair: "USDHUF", id: generateNumericId() },
  { pair: "USDILS", id: generateNumericId() },
  { pair: "USDINR", id: generateNumericId() },
  { pair: "USDMXN", id: generateNumericId() },
  { pair: "USDNOK", id: generateNumericId() },
  { pair: "USDPLN", id: generateNumericId() },
  { pair: "USDRON", id: generateNumericId() },
  { pair: "USDRUB", id: generateNumericId() },
  { pair: "USDSEK", id: generateNumericId() },
  { pair: "USDSGD", id: generateNumericId() },
  { pair: "USDTHB", id: generateNumericId() },
  { pair: "USDTRY", id: generateNumericId() },
  { pair: "USDZAR", id: generateNumericId() },
  { pair: "AUDHKD", id: generateNumericId() },
  { pair: "AUDMXN", id: generateNumericId() },
  { pair: "AUDNOK", id: generateNumericId() },
  { pair: "AUDPLN", id: generateNumericId() },
  { pair: "AUDSEK", id: generateNumericId() },
  { pair: "AEDJPY", id: generateNumericId() },
  { pair: "AUDCZK", id: generateNumericId() },
  { pair: "AUDDKK", id: generateNumericId() },
  { pair: "CHFAUD", id: generateNumericId() },
  { pair: "CHFDKK", id: generateNumericId() },
  { pair: "CHFSEK", id: generateNumericId() },
  { pair: "DKKAUD", id: generateNumericId() },
  { pair: "DKKCHF", id: generateNumericId() },
  { pair: "EURAUD", id: generateNumericId() },
  { pair: "EURNOK", id: generateNumericId() },
  { pair: "EURNZD", id: generateNumericId() },
  { pair: "HKDAUD", id: generateNumericId() },
  { pair: "HKDJPY", id: generateNumericId() },
  { pair: "INRAUD", id: generateNumericId() },
  { pair: "INRJPY", id: generateNumericId() },
  { pair: "JPYAUD", id: generateNumericId() },
  { pair: "JPYHKD", id: generateNumericId() },
  { pair: "JPYINR", id: generateNumericId() },
  { pair: "MXNAUD", id: generateNumericId() },
  { pair: "MXNJPY", id: generateNumericId() },
  { pair: "NOKAUD", id: generateNumericId() },
  { pair: "NOKJPY", id: generateNumericId() },
  { pair: "NZDCHF", id: generateNumericId() },
  { pair: "NZDCZK", id: generateNumericId() },
  { pair: "NZDDKK", id: generateNumericId() },
  { pair: "NZDHKD", id: generateNumericId() },
  { pair: "NZDILS", id: generateNumericId() },
  { pair: "NZDINR", id: generateNumericId() },
  { pair: "NZDMXN", id: generateNumericId() },
  { pair: "NZDNOK", id: generateNumericId() },
  { pair: "NZDPLN", id: generateNumericId() },
  { pair: "NZDSEK", id: generateNumericId() },
  { pair: "NZDSGD", id: generateNumericId() },
  { pair: "NZDTHB", id: generateNumericId() },
  { pair: "NZDTRY", id: generateNumericId() },
  { pair: "NZDZAR", id: generateNumericId() },
  { pair: "SEKAUD", id: generateNumericId() },
  { pair: "SEKJPY", id: generateNumericId() },
  { pair: "SGDAUD", id: generateNumericId() },
  { pair: "SGDCHF", id: generateNumericId() },
  { pair: "SGDJPY", id: generateNumericId() },
  { pair: "THBAUD", id: generateNumericId() },
  { pair: "THBJPY", id: generateNumericId() },
  { pair: "TRYJPY", id: generateNumericId() },
  { pair: "USDHUF", id: generateNumericId() },
  { pair: "USDILS", id: generateNumericId() },
  { pair: "USDMXN", id: generateNumericId() },
  { pair: "USDPLN", id: generateNumericId() },
  { pair: "USDSEK", id: generateNumericId() },
  { pair: "USDTHB", id: generateNumericId() },
  { pair: "USDTRY", id: generateNumericId() },
  { pair: "USDZAR", id: generateNumericId() },
  { pair: "ZARJPY", id: generateNumericId() },

  // Indices
  { pair: "US30", id: generateNumericId() }, // Dow Jones Industrial Average
  { pair: "SPX500", id: generateNumericId() }, // S&P 500
  { pair: "NAS100", id: generateNumericId() }, // Nasdaq 100
  { pair: "GER30", id: generateNumericId() }, // DAX 30
  { pair: "UK100", id: generateNumericId() }, // FTSE 100
  { pair: "JP225", id: generateNumericId() }, // Nikkei 225
  { pair: "AUS200", id: generateNumericId() }, // ASX 200
  { pair: "CAC40", id: generateNumericId() }, // CAC 40
  { pair: "HK50", id: generateNumericId() }, // Hang Seng Index
  { pair: "ES35", id: generateNumericId() }, // IBEX 35
  { pair: "IT40", id: generateNumericId() }, // FTSE MIB
  { pair: "CH20", id: generateNumericId() }, // Swiss Market Index

  // Metals
  { pair: "XAUUSD", id: generateNumericId() }, // Gold
  { pair: "XAGUSD", id: generateNumericId() }, // Silver
  { pair: "XPTUSD", id: generateNumericId() }, // Platinum
  { pair: "XPDUSD", id: generateNumericId() }, // Palladium
  { pair: "XAUEUR", id: generateNumericId() }, // Gold/EUR
  { pair: "XAGEUR", id: generateNumericId() }, // Silver/EUR
  { pair: "XAUGBP", id: generateNumericId() }, // Gold/GBP
  { pair: "XAGGBP", id: generateNumericId() }, // Silver/GBP
  { pair: "XAUJPY", id: generateNumericId() }, // Gold/JPY
  { pair: "XAGJPY", id: generateNumericId() }, // Silver/JPY
];
